name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the application directory on the GCE instance
            cd /path/to/your/app
            
            # Pull the latest code from the main branch
            git pull origin main
            
            # Install new dependencies (if any)
            # This assumes Python and pip are already installed on the VM
            pip install -r requirements.txt
            
            # Restart the application
            # This assumes you are using a process manager like systemd
            sudo systemctl restart your-fastapi-service
